from .game_settings import TILESIZE, SCREEN_WIDTH, SCREEN_HEIGHT

#Menu Settings
SIDE_MENU_W = 7*TILESIZE
SIDE_MENU_H = 18*TILESIZE
SIDE_MENU_X = SCREEN_WIDTH - SIDE_MENU_W
SIDE_MENU_Y = ((SCREEN_HEIGHT/TILESIZE - 18)/2)*TILESIZE