[sheet_data]
tile_w = 32
tile_h = 32
hit_box_w = 32
hit_box_h = 32

[idle_down]
frame_duration = 40
row = 6
seq = [0, 1, 2, 3]

[idle_up]
frame_duration = 40
row = 4
seq = [0, 1, 2, 3]

[idle_left]
frame_duration = 30
row = 5
seq = [0, 1, 2, 3]

[idle_right]
frame_duration = 30
row = 7
seq = [0, 1, 2, 3]

[walk_down]
frame_duration = 12
row = 2
seq = [0, 1, 2, 3]

[walk_up]
frame_duration = 12
row = 0
seq = [0, 1, 2, 3]

[walk_left]
frame_duration = 12
row = 1
seq = [0, 1, 2, 3]

[walk_right]
frame_duration = 12
row = 2
seq = [0, 1, 2, 3]

